---
# make name space exists before we create ServiceAccount
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "432037b7-1bda-45c0-a4b3-fad2adf0cfde"
  name: "workload-identity"
  namespace: "kube-system"
